### ISSUE TITLE
Decide on the design of the webpage

### ISSUE THREAD

**Issue by sivaraam** [sirganeshv/Seminar#1]
![20170113_154233](https://cloud.githubusercontent.com/assets/12448084/21937344/12e786bc-d9dd-11e6-839f-b241fbc82111.jpg)

**Comment by sirganeshv** [comment]
The template is good 
Shall i include the logo now itself ?

**Comment by sivaraam** [comment]
Your wish. 😉

**Comment by sivaraam** [comment]
closing in favour of #29.
